name: spider

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Node Spider
        run: |
          python spider/node.py
          ./commit.sh node-spider

      - name: Run Jdk Spider
        run: |
          python spider/jdk.py
          ./commit.sh jdk-spider

      - name: Run Jdk Latest Spider
        run: |
          python spider/jdk-latest.py
          ./commit.sh jdk-latest-spider
